/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 15-kvì-2016 17:53:12 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0 
;

/* Drop Tables */

DROP TABLE IF EXISTS `TaskActions` CASCADE
;

DROP TABLE IF EXISTS `TaskConditions` CASCADE
;

DROP TABLE IF EXISTS `TaskHistory` CASCADE
;

DROP TABLE IF EXISTS `Tasks` CASCADE
;

/* Create Tables */

CREATE TABLE `TaskActions`
(
	`TaskActionID` INTEGER NOT NULL AUTO_INCREMENT,
	`TaskID` INTEGER 	 NULL,
	`Type` VARCHAR(30) NOT NULL COMMENT 'Type of Action: iTask - run class with iTask interface',
	`Data` TEXT 	 NULL COMMENT 'Different from Type:  iTask - class name',
	`Order` INTEGER NOT NULL DEFAULT 1,
	CONSTRAINT `PK_TaskActions` PRIMARY KEY (`TaskActionID` ASC)
)

;

CREATE TABLE `TaskConditions`
(
	`TaskConditionID` INTEGER NOT NULL AUTO_INCREMENT,
	`TaskID` INTEGER NOT NULL,
	`Type` VARCHAR(30) NOT NULL,
	`Data` TEXT 	 NULL,
	`Created` DATETIME 	 NULL,
	`Expired` DATETIME 	 NULL,
	`Active` BOOL NOT NULL DEFAULT 1,
	CONSTRAINT `PK_TaskConditions` PRIMARY KEY (`TaskConditionID` ASC)
)

;

CREATE TABLE `TaskHistory`
(
	`TaskHistoryID` INTEGER NOT NULL AUTO_INCREMENT,
	`TaskID` INTEGER NOT NULL,
	`Started` DATETIME NOT NULL,
	`Finished` DATETIME 	 NULL,
	`ResultCode` INTEGER 	 NULL,
	`User` VARCHAR(150) 	 NULL,
	`Output` TEXT 	 NULL,
	CONSTRAINT `PK_TaskHistory` PRIMARY KEY (`TaskHistoryID` ASC)
)

;

CREATE TABLE `Tasks`
(
	`TaskID` INTEGER NOT NULL AUTO_INCREMENT,
	`Name` VARCHAR(150) NOT NULL,
	`Created` DATETIME NOT NULL,
	`Source` VARCHAR(255) 	 NULL,
	`Author` VARCHAR(100) 	 NULL,
	`Description` TEXT 	 NULL,
	`DeleteAfterRun` BOOL NOT NULL DEFAULT 0,
	`MaxExecutionTimeInSecond` INTEGER 	 NULL,
	`Disabled` BOOL NOT NULL DEFAULT 0,
	`State` INTEGER NOT NULL DEFAULT 0 COMMENT '0 = Idle 1 = Running 2 = Queued',
	`ExceedDateTime` DATETIME 	 NULL,
	`NextRun` DATETIME 	 NULL,
	`LastRun` DATETIME 	 NULL,
	`LastSuccess` INTEGER 	 NULL,
	`Deleted` BOOL NOT NULL DEFAULT 0,
	CONSTRAINT `PK_Task` PRIMARY KEY (`TaskID` ASC)
)

;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `TaskActions` 
 ADD INDEX `IXFK_TaskActions_Tasks` (`TaskID` ASC)
;

ALTER TABLE `TaskActions` 
 ADD INDEX `IDX_TaskActions_Order` (`Order` ASC)
;

ALTER TABLE `TaskConditions` 
 ADD INDEX `IXFK_TaskConditions_Tasks` (`TaskID` ASC)
;

ALTER TABLE `TaskConditions` 
 ADD INDEX `IDX_TaskConditions_Type` (`Type` ASC)
;

ALTER TABLE `TaskConditions` 
 ADD INDEX `IDX_TaskConditions_Active` (`Active` ASC)
;

ALTER TABLE `TaskHistory` 
 ADD INDEX `IXFK_TaskHistory_Tasks` (`TaskID` ASC)
;

ALTER TABLE `TaskHistory` 
 ADD INDEX `IDX_ResultCode` (`ResultCode` ASC)
;

ALTER TABLE `Tasks` 
 ADD INDEX `IDX_Task_Name` (`Name` ASC)
;

ALTER TABLE `Tasks` 
 ADD INDEX `IDX_Task_Deleted` (`Deleted` ASC)
;

ALTER TABLE `Tasks` 
 ADD INDEX `IDX_Task_DeletedAfterRun` (`DeleteAfterRun` ASC)
;

ALTER TABLE `Tasks` 
 ADD INDEX `IDX_Task_Running` (`State` ASC)
;

ALTER TABLE `Tasks` 
 ADD INDEX `IDX_Task_NextRun` (`NextRun` ASC)
;

ALTER TABLE `Tasks` 
 ADD INDEX `IDX_Task_Source` (`Source` ASC)
;

ALTER TABLE `Tasks` 
 ADD INDEX `IDX_Task_Disabled` (`Disabled` ASC)
;

ALTER TABLE `Tasks` 
 ADD INDEX `IDX_Task_LastSuccess` (`LastSuccess` ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE `TaskActions` 
 ADD CONSTRAINT `FK_TaskActions_Tasks`
	FOREIGN KEY (`TaskID`) REFERENCES `Tasks` (`TaskID`) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE `TaskConditions` 
 ADD CONSTRAINT `FK_TaskConditions_Tasks`
	FOREIGN KEY (`TaskID`) REFERENCES `Tasks` (`TaskID`) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE `TaskHistory` 
 ADD CONSTRAINT `FK_TaskHistory_Tasks`
	FOREIGN KEY (`TaskID`) REFERENCES `Tasks` (`TaskID`) ON DELETE No Action ON UPDATE No Action
;

SET FOREIGN_KEY_CHECKS=1 
;
