/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 06-úno-2016 20:10:15 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Foreign Key Constraints */

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_TaskConditions_Tasks]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [TaskConditions] DROP CONSTRAINT [FK_TaskConditions_Tasks]
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_TaskActions_Tasks]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [TaskActions] DROP CONSTRAINT [FK_TaskActions_Tasks]
GO

/* Drop Tables */

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[Tasks]') AND OBJECTPROPERTY(id, 'IsUserTable') = 1) 
DROP TABLE [Tasks]
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[TaskConditions]') AND OBJECTPROPERTY(id, 'IsUserTable') = 1) 
DROP TABLE [TaskConditions]
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[TaskActions]') AND OBJECTPROPERTY(id, 'IsUserTable') = 1) 
DROP TABLE [TaskActions]
GO

/* Create Tables */

CREATE TABLE [Tasks]
(
	[TaskID] int NOT NULL IDENTITY (1, 1),
	[Name] varchar(150) NOT NULL,
	[Created] datetime NOT NULL,
	[Source] varchar(255) NULL,
	[Author] varchar(100) NULL,
	[Description] text NULL,
	[DeleteAfterRun] bit NOT NULL DEFAULT 0,
	[Disabled] bit NOT NULL DEFAULT 0,
	[State] int NOT NULL DEFAULT 0,    -- 0 = Idle 1 = Running 2 = Queued
	[NextRun] datetime NULL,
	[LastRun] datetime NULL,
	[LastSuccess] bit NULL,
	[Deleted] bit NOT NULL DEFAULT 0
)
GO

CREATE TABLE [TaskConditions]
(
	[TaskConditionID] int NOT NULL IDENTITY (1, 1),
	[TaskID] int NOT NULL,
	[Type] varchar(30) NOT NULL,
	[Data] text NULL,
	[Created] datetime NULL,
	[Expired] datetime NULL,
	[Active] bit NOT NULL DEFAULT 1
)
GO

CREATE TABLE [TaskActions]
(
	[TaskActionID] int NOT NULL IDENTITY (1, 1),
	[TaskID] int NULL,
	[Type] varchar(30) NOT NULL,    -- Type of Action: iTask - run class with iTask interface
	[Data] text NULL,    -- Different from Type:  iTask - class name
	[Order] int NOT NULL DEFAULT 1
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [Tasks] 
 ADD CONSTRAINT [PK_Task]
	PRIMARY KEY CLUSTERED ([TaskID])
GO

CREATE INDEX [IDX_Task_Name] 
 ON [Tasks] ([Name] ASC)
GO

CREATE INDEX [IDX_Task_Deleted] 
 ON [Tasks] ([Deleted] ASC)
GO

CREATE INDEX [IDX_Task_DeletedAfterRun] 
 ON [Tasks] ([DeleteAfterRun] ASC)
GO

CREATE INDEX [IDX_Task_Running] 
 ON [Tasks] ([State] ASC)
GO

CREATE INDEX [IDX_Task_NextRun] 
 ON [Tasks] ([NextRun] ASC)
GO

CREATE INDEX [IDX_Task_Source] 
 ON [Tasks] ([Source] ASC)
GO

CREATE INDEX [IDX_Task_Disabled] 
 ON [Tasks] ([Disabled] ASC)
GO

CREATE INDEX [IDX_Task_LastSuccess] 
 ON [Tasks] ([LastSuccess] ASC)
GO

ALTER TABLE [TaskConditions] 
 ADD CONSTRAINT [PK_TaskConditions]
	PRIMARY KEY CLUSTERED ([TaskConditionID])
GO

CREATE INDEX [IXFK_TaskConditions_Tasks] 
 ON [TaskConditions] ([TaskID] ASC)
GO

CREATE INDEX [IDX_TaskConditions_Type] 
 ON [TaskConditions] ([Type] ASC)
GO

CREATE INDEX [IDX_TaskConditions_Active] 
 ON [TaskConditions] ([Active] ASC)
GO

ALTER TABLE [TaskActions] 
 ADD CONSTRAINT [PK_TaskActions]
	PRIMARY KEY CLUSTERED ([TaskActionID])
GO

CREATE INDEX [IXFK_TaskActions_Tasks] 
 ON [TaskActions] ([TaskID] ASC)
GO

CREATE INDEX [IDX_TaskActions_Order] 
 ON [TaskActions] ([Order] ASC)
GO

/* Create Foreign Key Constraints */

ALTER TABLE [TaskConditions] ADD CONSTRAINT [FK_TaskConditions_Tasks]
	FOREIGN KEY ([TaskID]) REFERENCES [Tasks] ([TaskID]) ON DELETE Cascade ON UPDATE Cascade
GO

ALTER TABLE [TaskActions] ADD CONSTRAINT [FK_TaskActions_Tasks]
	FOREIGN KEY ([TaskID]) REFERENCES [Tasks] ([TaskID]) ON DELETE Cascade ON UPDATE Cascade
GO

/* Create Table Comments */

EXEC sp_addextendedproperty 'MS_Description', '0 = Idle 1 = Running 2 = Queued', 'Schema', [dbo], 'table', [Tasks], 'column', [State]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Type of Action: iTask - run class with iTask interface', 'Schema', [dbo], 'table', [TaskActions], 'column', [Type]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Different from Type:  iTask - class name', 'Schema', [dbo], 'table', [TaskActions], 'column', [Data]
GO
