/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 21-lis-2016 10:12:27 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0 
;

/* Drop Tables */

DROP TABLE IF EXISTS `TaskActions` CASCADE
;

/* Create Tables */

CREATE TABLE `TaskActions`
(
	`TaskActionID` INTEGER NOT NULL AUTO_INCREMENT,
	`TaskID` INTEGER 	 NULL,
	`Type` VARCHAR(30) NOT NULL COMMENT 'Type of Action: iTask - run class with iTask interface',
	`Data` TEXT 	 NULL COMMENT 'Different from Type:  iTask - class name',
	`Order` INTEGER NOT NULL DEFAULT 1,
	CONSTRAINT `PK_TaskActions` PRIMARY KEY (`TaskActionID` ASC)
)

;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `TaskActions` 
 ADD INDEX `IXFK_TaskActions_Tasks` (`TaskID` ASC)
;

ALTER TABLE `TaskActions` 
 ADD INDEX `IDX_TaskActions_Order` (`Order` ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE `TaskActions` 
 ADD CONSTRAINT `FK_TaskActions_Tasks`
	FOREIGN KEY (`TaskID`) REFERENCES `Tasks` (`TaskID`) ON DELETE Cascade ON UPDATE Cascade
;

SET FOREIGN_KEY_CHECKS=1 
;