/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 21-lis-2016 10:12:27 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0 
;

/* Drop Tables */

DROP TABLE IF EXISTS `TaskHistory` CASCADE
;

/* Create Tables */

CREATE TABLE `TaskHistory`
(
	`TaskHistoryID` INTEGER NOT NULL AUTO_INCREMENT,
	`TaskID` INTEGER NOT NULL,
	`Started` DATETIME NOT NULL,
	`Finished` DATETIME 	 NULL,
	`ResultCode` INTEGER 	 NULL,
	`User` VARCHAR(150) 	 NULL,
	`Output` TEXT 	 NULL,
	CONSTRAINT `PK_TaskHistory` PRIMARY KEY (`TaskHistoryID` ASC)
)

;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `TaskHistory` 
 ADD INDEX `IXFK_TaskHistory_Tasks` (`TaskID` ASC)
;

ALTER TABLE `TaskHistory` 
 ADD INDEX `IDX_ResultCode` (`ResultCode` ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE `TaskHistory` 
 ADD CONSTRAINT `FK_TaskHistory_Tasks`
	FOREIGN KEY (`TaskID`) REFERENCES `Tasks` (`TaskID`) ON DELETE No Action ON UPDATE No Action
;

SET FOREIGN_KEY_CHECKS=1 
;