/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 21-lis-2016 10:12:27 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0 
;

/* Drop Tables */

DROP TABLE IF EXISTS `TaskConditions` CASCADE
;

/* Create Tables */

CREATE TABLE `TaskConditions`
(
	`TaskConditionID` INTEGER NOT NULL AUTO_INCREMENT,
	`TaskID` INTEGER NOT NULL,
	`Type` VARCHAR(30) NOT NULL,
	`Data` TEXT 	 NULL,
	`Created` DATETIME 	 NULL,
	`Expired` DATETIME 	 NULL,
	`Active` TINYINT NOT NULL DEFAULT 1,
	CONSTRAINT `PK_TaskConditions` PRIMARY KEY (`TaskConditionID` ASC)
)

;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `TaskConditions` 
 ADD INDEX `IXFK_TaskConditions_Tasks` (`TaskID` ASC)
;

ALTER TABLE `TaskConditions` 
 ADD INDEX `IDX_TaskConditions_Type` (`Type` ASC)
;

ALTER TABLE `TaskConditions` 
 ADD INDEX `IDX_TaskConditions_Active` (`Active` ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE `TaskConditions` 
 ADD CONSTRAINT `FK_TaskConditions_Tasks`
	FOREIGN KEY (`TaskID`) REFERENCES `Tasks` (`TaskID`) ON DELETE Cascade ON UPDATE Cascade
;

SET FOREIGN_KEY_CHECKS=1 
;