/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 21-lis-2016 10:13:03 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Foreign Key Constraints */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_TaskHistory_Tasks]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [TaskHistory] DROP CONSTRAINT [FK_TaskHistory_Tasks]
GO

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[TaskHistory]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [TaskHistory]
GO

/* Create Tables */

CREATE TABLE [TaskHistory]
(
	[TaskHistoryID] int NOT NULL IDENTITY (1, 1),
	[TaskID] int NOT NULL,
	[Started] datetime NOT NULL,
	[Finished] datetime NULL,
	[ResultCode] int NULL,
	[User] varchar(150) NULL,
	[Output] text NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [TaskHistory] 
 ADD CONSTRAINT [PK_TaskHistory]
	PRIMARY KEY CLUSTERED ([TaskHistoryID] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_TaskHistory_Tasks] 
 ON [TaskHistory] ([TaskID] ASC)
GO

CREATE NONCLUSTERED INDEX [IDX_ResultCode] 
 ON [TaskHistory] ([ResultCode] ASC)
GO

/* Create Foreign Key Constraints */

ALTER TABLE [TaskHistory] ADD CONSTRAINT [FK_TaskHistory_Tasks]
	FOREIGN KEY ([TaskID]) REFERENCES [Tasks] ([TaskID]) ON DELETE No Action ON UPDATE No Action
GO