/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 21-lis-2016 10:13:03 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Foreign Key Constraints */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_TaskConditions_Tasks]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [TaskConditions] DROP CONSTRAINT [FK_TaskConditions_Tasks]
GO

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[TaskConditions]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [TaskConditions]
GO

/* Create Tables */

CREATE TABLE [TaskConditions]
(
	[TaskConditionID] int NOT NULL IDENTITY (1, 1),
	[TaskID] int NOT NULL,
	[Type] varchar(30) NOT NULL,
	[Data] text NULL,
	[Created] datetime NULL,
	[Expired] datetime NULL,
	[Active] bit NOT NULL DEFAULT 1
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [TaskConditions] 
 ADD CONSTRAINT [PK_TaskConditions]
	PRIMARY KEY CLUSTERED ([TaskConditionID] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_TaskConditions_Tasks] 
 ON [TaskConditions] ([TaskID] ASC)
GO

CREATE NONCLUSTERED INDEX [IDX_TaskConditions_Type] 
 ON [TaskConditions] ([Type] ASC)
GO

CREATE NONCLUSTERED INDEX [IDX_TaskConditions_Active] 
 ON [TaskConditions] ([Active] ASC)
GO

/* Create Foreign Key Constraints */

ALTER TABLE [TaskConditions] ADD CONSTRAINT [FK_TaskConditions_Tasks]
	FOREIGN KEY ([TaskID]) REFERENCES [Tasks] ([TaskID]) ON DELETE Cascade ON UPDATE Cascade
GO