/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 21-lis-2016 10:13:03 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Tasks]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Tasks]
GO

/* Create Tables */

CREATE TABLE [Tasks]
(
	[TaskID] int NOT NULL IDENTITY (1, 1),
	[Name] varchar(150) NOT NULL,
	[Created] datetime NOT NULL,
	[Source] varchar(255) NULL,
	[Author] varchar(100) NULL,
	[Description] text NULL,
	[DeleteAfterRun] bit NOT NULL DEFAULT 0,
	[MaxExecutionTimeInSecond] int NULL,
	[Disabled] bit NOT NULL DEFAULT 0,
	[State] int NOT NULL DEFAULT 0,    -- 0 = Idle 1 = Running 2 = Queued
	[ExceedDateTime] datetime NULL,
	[NextRun] datetime NULL,
	[LastRun] datetime NULL,
	[LastSuccess] int NULL,
	[Deleted] bit NOT NULL DEFAULT 0
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [Tasks] 
 ADD CONSTRAINT [PK_Task]
	PRIMARY KEY CLUSTERED ([TaskID] ASC)
GO

CREATE NONCLUSTERED INDEX [IDX_Task_Name] 
 ON [Tasks] ([Name] ASC)
GO

CREATE NONCLUSTERED INDEX [IDX_Task_Deleted] 
 ON [Tasks] ([Deleted] ASC)
GO

CREATE NONCLUSTERED INDEX [IDX_Task_DeletedAfterRun] 
 ON [Tasks] ([DeleteAfterRun] ASC)
GO

CREATE NONCLUSTERED INDEX [IDX_Task_Running] 
 ON [Tasks] ([State] ASC)
GO

CREATE NONCLUSTERED INDEX [IDX_Task_NextRun] 
 ON [Tasks] ([NextRun] ASC)
GO

CREATE NONCLUSTERED INDEX [IDX_Task_Source] 
 ON [Tasks] ([Source] ASC)
GO

CREATE NONCLUSTERED INDEX [IDX_Task_Disabled] 
 ON [Tasks] ([Disabled] ASC)
GO

CREATE NONCLUSTERED INDEX [IDX_Task_LastSuccess] 
 ON [Tasks] ([LastSuccess] ASC)
GO

/* Create Table Comments */

EXEC sp_addextendedproperty 'MS_Description', '0 = Idle 1 = Running 2 = Queued', 'Schema', [dbo], 'table', [Tasks], 'column', [State]
GO